name: Build Tests

on:
  pull_request:
    branches: 
    - master
jobs:
  build_test_x64:
    name: Running Build Test for x64
    runs-on: [ubuntu-18.04] 
    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v2
      - name: Running build test script for x64
        run: ./package.sh -b
