name: Docker Image CI

on:
  pull_request:
    branches: 
    - master
jobs:
  build_test:
    name: Running Build Test
    runs-on: [ubuntu-18.04] 
    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v2
        
      - name: Checking src location
        run: ls
      
      - name: Running build test script
        run: ./package.sh -b
